# This is an example of a CI workflow with npm ci and Node 18 setup

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm ci --legacy-peer-deps
    - name: Run Tests
      run: npm test